apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-julian-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-julian
  template:
    metadata:
      labels:
        app: producer-julian
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: producer
                    operator: In
                    values:
                      - julian
      containers:
        - name: producer-julian-container
          image: julianrc1/producer-julian:latest
          ports:
            - containerPort: 4000
          env:
            - name: KAFKA_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: kafka_address
            - name: TOPIC_NAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: topic_name

---
apiVersion: v1
kind: Service
metadata:
  name: producer-julian-service
spec:
  selector:
    app: producer-julian
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400
  type: NodePort
