apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: kafka
type: Opaque
data:
  kafka_address: bXktY2x1c3Rlci1rYWZrYS1ib290c3RyYXAua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
  topic_name: dW5pdmFsbGU=